# 3 NumPy

## 1. Создайте numpy.ndarray размерностью 3x4x2 и продемонстрируйте разные способы обращения по индексам из документации NumPy.

In [53]:
import numpy as np

In [54]:
a = np.ones((3,4,2))

In [55]:
a

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [56]:
print(a.ndim)
print(a.shape)

3
(3, 4, 2)


In [57]:
a[0,0,0] = 5
a[2,1,0] = 7

In [58]:
a


array([[[5., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [7., 1.],
        [1., 1.],
        [1., 1.]]])

In [59]:
a[0,0]

array([5., 1.])

In [20]:
for i in range(2):
    print(a[i,i,i])

5.0
1.0


## 2. Попробуйте сравнить по производительности numpy.array и list, выполняя какую-то стандартную операцию с каждым из типов много раз.


In [65]:
a = np.arange(0,100_000)
l = [i for i in range(100_000)]


In [66]:
import time
start_time = time.time()
a = a**2
print("--- %s seconds ---" % (time.time() - start_time))

--- 0.0009982585906982422 seconds ---


In [69]:
import time
start_time = time.time()
l = [l[i]**2 for i in range(len(l))]
print("--- %s seconds ---" % (time.time() - start_time))


--- 0.052971839904785156 seconds ---


### numpy array намного быстрее

## 3. Изучите numpy.linspace(), напишите свою реализацию аналогичной функции с помощью list comprehension, дающий тот же результат, только в виде list, а не numpy.ndarray. Сравните по производительности два варианта на достаточно больших массивах.

In [104]:
a = np.linspace(1,100_000, 10000)

In [110]:
a

array([1.00000000e+00, 1.10009001e+01, 2.10018002e+01, ...,
       9.99799982e+04, 9.99899991e+04, 1.00000000e+05])

In [111]:
def linspace(start,stop,num):
    step = float(stop-start)/float(num)
    list = [start + step*i for i in range(0,stop)]
    return list
    

In [112]:
linspace(1,100_000,10000)


[1.0,
 10.9999,
 20.9998,
 30.9997,
 40.9996,
 50.9995,
 60.9994,
 70.9993,
 80.9992,
 90.9991,
 100.999,
 110.9989,
 120.9988,
 130.9987,
 140.9986,
 150.9985,
 160.9984,
 170.9983,
 180.9982,
 190.9981,
 200.998,
 210.99790000000002,
 220.9978,
 230.9977,
 240.9976,
 250.9975,
 260.9974,
 270.9973,
 280.9972,
 290.9971,
 300.997,
 310.9969,
 320.9968,
 330.99670000000003,
 340.9966,
 350.9965,
 360.9964,
 370.9963,
 380.9962,
 390.9961,
 400.996,
 410.9959,
 420.99580000000003,
 430.9957,
 440.9956,
 450.9955,
 460.9954,
 470.9953,
 480.9952,
 490.99510000000004,
 500.995,
 510.99490000000003,
 520.9948,
 530.9947,
 540.9946,
 550.9945,
 560.9944,
 570.9943000000001,
 580.9942,
 590.9941,
 600.994,
 610.9939,
 620.9938,
 630.9937,
 640.9936,
 650.9935,
 660.9934000000001,
 670.9933,
 680.9932,
 690.9931,
 700.993,
 710.9929,
 720.9928,
 730.9927,
 740.9926,
 750.9925000000001,
 760.9924,
 770.9923,
 780.9922,
 790.9921,
 800.992,
 810.9919,
 820.9918,
 830.9917,
 840.9916000000001,
 

In [113]:
import time
start_time = time.time()
a = np.linspace(1,100_000, 100)
print("--- %s seconds ---" % (time.time() - start_time))

--- 0.0 seconds ---


In [114]:
import time
start_time = time.time()
linspace(1,100_000,100)
print("--- %s seconds ---" % (time.time() - start_time))

--- 0.03497934341430664 seconds ---


### numpy опять быстрее